### ISSUE TITLE
拉流时提示“illegal rtmp url”

### ISSUE THREAD

**Issue by sultra** [Monibuca/plugin-rtmp#27]
如题，rtmp url 在vlc,IINA 中能播放
url如：`rtmp://<host>:<port>/domain=31010600012000000000&resource=31010600011320001122-0&quality=2&src=1`
使用api rtmp/api/pull urlencode 过编码 也是不行，同样错误（后台能输出能看到正确的url地址）

音视频编码：H264 - MPEG-4 AVC (part 10) (avc1) /  MPEG AAC Audio (mp4a)

**Comment by langhuihui** [comment]
你 pull 的时候需要指定 streamPath，这个 streamPath 你指定了什么。如果正常是可以转成 flv 的。

**Comment by sultra** [comment]
> 你 pull 的时候需要指定 streamPath，这个 streamPath 你指定了什么。如果正常是可以转成 flv 的。

api 方式没有，配置文件方式是写了,如下
``` yaml
rtmp:
  enable: true
  chunksize: 65536
  keepalive: false
  pull:
    repull: 10
    pullonsub:
      live/c1: rtmp://<host>:<port>/domain=31010600012000000000&resource=31010600011320001122-0&quality=2&src=1
```
